name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mypy bandit pycodestyle
    - name: Analysing the code with pylint
      run: |
        bandit $(git ls-files '*.py')
        pycodestyle $(git ls-files '*.py') -v
        mypy --show-error-codes $(git ls-files '*.py')
